---
# tasks file for maas

- name: install package through snap
  snap:
     name:
        - maas
        - maas-test-db
     state: present
     channel: 2.8/stable

- name: install pip3
  apt:
    name: 
      - python3-pip
      - network-manager
      - bridge-utils
      - qemu-kvm
      - qemu
      - virt-manager
      - mlocate
      - net-tools
    state: present
    update_cache: yes

- name: install pexpect
  pip:
    name: pexpect

- name: craete a bridge adapter
  copy:
     src: 01-netcfg.yml
     dest: /etc/netplan/01-netcfg.yml

- name: create the adapter
  command: netplan apply

- name: destroy default adapter
  command:
       - virsh net-destroy default
       - virsh net-undefine default

- name: replace the default adapter
  command:
        - virsh net-define maas.xml
        - virsh net-autostart default
        - virsh net-start default

- name: initalize the maas
  expect:
     command: sudo maas init {{ mode }} --database-uri maas-test-db:///
     responses:
            "MAAS": "{{ maas_url }}"
     timeout: 240
     echo: yes

- name: create admin
  expect:
      command: sudo maas createadmin
      responses:
            "Username": "{{ username }}"
            "Password": "{{ password }}"
            "Again": "{{ password }}"
            "Email": "{{ email }}"
            "Import": "\n"
      echo: yes

- name: login to maas
  shell: sudo maas login {{ username }} {{ maas_url }} $(maas apikey --username {{ username }} )


